language: go

go: master

services: docker

before_script:
  - cd scripts/ && \
  - ./ci-up.sh ${PWD}

script:
  - cd ../ && \
  - go test -v ./...

after_script:
  - cd scripts/ && \
  - ./ci-down.sh
