language: go

go: master

services: docker

before_install:
  - echo $TRAVIS_BRANCH
  - docker build -t project_aurum:version1.0 --build-arg BRANCH=$TRAVIS_BRANCH .
  - docker run -d -p 62000:62000 project_aurum:version1.0

# script: go test `go list ./... | grep -v main` -v ./...
script: 
  - go test -v ./...

after_script:
  - docker rmi -f project_aurum:version1.0
  - docker container stop $(docker container ls -aq)
  - docker container rm $(docker container ls -aq)