language: go

go: master

services: docker

before_install:
  - echo $TRAVIS_BRANCH
  - docker build -t project_aurum:version1.0 --build-arg BRANCH=$TRAVIS_BRANCH --build-arg WALLET_ADDRS="23aafe84f813bd5093599691ea5731425effe1b8c3f7c1e3c049012558160b8c 617af9da0ea3053e89ce43e1514640bcd41a3bd69810ca0f0d82e5cf8b4cadb8" .
  - docker run -d -p 62000:62000 project_aurum:version1.0
  
script: 
  - go test -v ./...

after_script:
  - docker rmi -f project_aurum:version1.0
  - docker container stop $(docker container ls -aq)
  - docker container rm $(docker container ls -aq)