language: go

go: master

services: docker

before_install:
  - echo $TRAVIS_BRANCH
  - docker-compose -f docker-compose.ci.yml build --build-arg BRANCH=$TRAVIS_BRANCH
  - docker-compose -f docker-compose.ci.yml up -d
  
script: 
  - go test -v ./...

after_script:
  - docker-compose -f docker-compose.ci.yml down
  - docker system prune -a -f