language: go

go: master

services: docker

before_install:
  - docker build -t project_aurum --build-arg BRANCH=$TRAVIS_BRANCH .

# script: go test `go list ./... | grep -v main` -v ./...
script: 
  - go test -v ./...
  - docker rmi -f project_aurum