version: '3'

services:
  aurum_producer:
    build:
      context: .
    ports: 
      - "26000:26000"
    container_name: "producer"
    volumes:
      - "${PWD}/../data/:/go/src/github.com/SIGBlockchain/project_aurum/data/"
